from copy import deepcopy
from typing import Any


_RISK_RANK = {"critical": 0, "high": 1, "medium": 2}


_POLICIES: tuple[dict[str, Any], ...] = (
    {
        "operation_key": "knowledge.rebuild_index",
        "module": "knowledge",
        "action": "rebuild_index",
        "title": "Rebuild knowledge vector index",
        "description": "Requeues vector index generation for the knowledge base.",
        "risk_level": "critical",
        "target_type": "knowledge_index",
        "requires_confirmation": True,
        "requires_dual_approval": True,
        "audit_event": "knowledge.rebuild_index",
        "audit_fields": [
            "request_id",
            "target_type",
            "result_status",
            "metadata_json.total",
            "metadata_json.failed",
        ],
        "current_enforcement": [
            "admin role",
            "structured audit event",
            "bounded result metadata",
        ],
        "next_controls": [
            "second admin approval before execution",
            "pre-change index snapshot",
            "rollback to previous active index",
        ],
        "rollback_hint": "Restore the previous vector index artifact and rerun the smoke evaluation gate.",
    },
    {
        "operation_key": "prompt.set_default",
        "module": "prompt",
        "action": "set_default",
        "title": "Switch default model prompt",
        "description": "Changes the default prompt template used by AI analysis.",
        "risk_level": "critical",
        "target_type": "prompt_template",
        "requires_confirmation": True,
        "requires_dual_approval": True,
        "audit_event": "prompt.set_default",
        "audit_fields": [
            "request_id",
            "target_type",
            "target_id",
            "result_status",
            "metadata_json.type",
        ],
        "current_enforcement": [
            "admin role",
            "prompt validation",
            "structured audit event",
        ],
        "next_controls": [
            "approval note with evaluation evidence",
            "AI engineering gate before production use",
            "one-click restore previous default",
        ],
        "rollback_hint": "Set the previous prompt template as default and rerun AI engineering regression cases.",
    },
    {
        "operation_key": "user.update_role",
        "module": "admin",
        "action": "update_user_role",
        "title": "Change user role",
        "description": "Promotes or demotes a user between normal and admin roles.",
        "risk_level": "critical",
        "target_type": "user",
        "requires_confirmation": True,
        "requires_dual_approval": True,
        "audit_event": "admin.update_user_role",
        "audit_fields": [
            "request_id",
            "target_type",
            "target_id",
            "result_status",
            "metadata_json.role",
        ],
        "current_enforcement": [
            "admin role",
            "last-admin guard",
            "self-demotion guard",
            "structured audit event",
        ],
        "next_controls": [
            "second admin approval for privilege escalation",
            "admin session re-authentication",
            "role-change notification",
        ],
        "rollback_hint": "Restore the previous role from audit context and invalidate active sessions for the user.",
    },
    {
        "operation_key": "report.delete",
        "module": "report",
        "action": "delete",
        "title": "Delete generated report record",
        "description": "Removes a report record and clears its detection report link.",
        "risk_level": "high",
        "target_type": "report",
        "requires_confirmation": True,
        "requires_dual_approval": False,
        "audit_event": "report.delete",
        "audit_fields": [
            "request_id",
            "target_type",
            "target_id",
            "result_status",
        ],
        "current_enforcement": [
            "admin role",
            "UI confirmation",
            "structured audit event",
            "linked detection cleanup",
        ],
        "next_controls": [
            "soft-delete retention window",
            "delete reason capture",
            "report file quarantine before purge",
        ],
        "rollback_hint": "Regenerate the report from the linked detection if source data is still retained.",
    },
    {
        "operation_key": "detection.delete",
        "module": "admin",
        "action": "delete_detection",
        "title": "Delete detection record",
        "description": "Deletes a user detection history record from the admin console.",
        "risk_level": "high",
        "target_type": "detection",
        "requires_confirmation": True,
        "requires_dual_approval": False,
        "audit_event": "admin.delete_detection",
        "audit_fields": [
            "request_id",
            "target_type",
            "target_id",
            "result_status",
        ],
        "current_enforcement": [
            "admin role",
            "structured audit event",
        ],
        "next_controls": [
            "UI confirmation",
            "soft-delete retention window",
            "delete reason capture",
        ],
        "rollback_hint": "Restore from database backup or replay the original detection request if available.",
    },
    {
        "operation_key": "knowledge.delete",
        "module": "knowledge",
        "action": "delete",
        "title": "Delete knowledge item",
        "description": "Removes a curated knowledge item and its vector representation.",
        "risk_level": "high",
        "target_type": "knowledge_item",
        "requires_confirmation": True,
        "requires_dual_approval": False,
        "audit_event": "knowledge.delete",
        "audit_fields": [
            "request_id",
            "target_type",
            "target_id",
            "result_status",
        ],
        "current_enforcement": [
            "admin role",
            "vector sync guard",
            "structured audit event",
        ],
        "next_controls": [
            "soft-delete and restore",
            "knowledge diff preview",
            "RAG regression case after deletion",
        ],
        "rollback_hint": "Recreate the knowledge item from audit/export data and re-vectorize it.",
    },
    {
        "operation_key": "prompt.delete",
        "module": "prompt",
        "action": "delete",
        "title": "Delete prompt template",
        "description": "Deletes a non-default prompt template.",
        "risk_level": "high",
        "target_type": "prompt_template",
        "requires_confirmation": True,
        "requires_dual_approval": False,
        "audit_event": "prompt.delete",
        "audit_fields": [
            "request_id",
            "target_type",
            "target_id",
            "result_status",
        ],
        "current_enforcement": [
            "admin role",
            "default prompt delete guard",
            "structured audit event",
        ],
        "next_controls": [
            "prompt archive instead of hard delete",
            "delete reason capture",
            "restore from archived revision",
        ],
        "rollback_hint": "Restore the template body from repository history or audit export, then validate it.",
    },
    {
        "operation_key": "user.disable",
        "module": "admin",
        "action": "disable_user",
        "title": "Disable user account",
        "description": "Disables a user account from the admin console.",
        "risk_level": "high",
        "target_type": "user",
        "requires_confirmation": True,
        "requires_dual_approval": False,
        "audit_event": "admin.disable_user",
        "audit_fields": [
            "request_id",
            "target_type",
            "target_id",
            "result_status",
        ],
        "current_enforcement": [
            "admin role",
            "last-admin guard",
            "self-operation guard",
            "structured audit event",
        ],
        "next_controls": [
            "disable reason capture",
            "active session revocation",
            "user notification",
        ],
        "rollback_hint": "Re-enable the account and review audit entries for any missed session revocation.",
    },
    {
        "operation_key": "high_risk.review",
        "module": "high_risk",
        "action": "review",
        "title": "Review high-risk detection",
        "description": "Marks high-risk AI detection output as reviewed.",
        "risk_level": "medium",
        "target_type": "detection",
        "requires_confirmation": False,
        "requires_dual_approval": False,
        "audit_event": "high_risk.review",
        "audit_fields": [
            "request_id",
            "target_type",
            "target_id",
            "result_status",
        ],
        "current_enforcement": [
            "admin role",
            "structured audit event",
        ],
        "next_controls": [
            "review note quality check",
            "reviewer workload metrics",
        ],
        "rollback_hint": "Update the review state and append a corrective remark to the detection record.",
    },
    {
        "operation_key": "high_risk.update_public",
        "module": "high_risk",
        "action": "update_public",
        "title": "Change public visibility of high-risk result",
        "description": "Controls whether a high-risk detection is visible in public views.",
        "risk_level": "high",
        "target_type": "detection",
        "requires_confirmation": True,
        "requires_dual_approval": False,
        "audit_event": "high_risk.update_public",
        "audit_fields": [
            "request_id",
            "target_type",
            "target_id",
            "result_status",
            "metadata_json.is_public",
        ],
        "current_enforcement": [
            "admin role",
            "structured audit event",
        ],
        "next_controls": [
            "UI confirmation",
            "reason capture",
            "public-change notification",
        ],
        "rollback_hint": "Revert the visibility flag and capture the correction in the operation remark.",
    },
)


def list_admin_operation_policies(risk_level: str | None = None) -> list[dict[str, Any]]:
    normalized_risk = risk_level.lower() if risk_level else None
    policies = [
        policy
        for policy in _POLICIES
        if normalized_risk is None or policy["risk_level"] == normalized_risk
    ]
    policies = sorted(
        policies,
        key=lambda policy: (
            _RISK_RANK.get(policy["risk_level"], 99),
            policy["operation_key"],
        ),
    )
    return deepcopy(policies)
