RISK_LEVEL_TRUSTED = "可信新闻"
RISK_LEVEL_SUSPICIOUS = "存疑信息"
RISK_LEVEL_RUMOR = "疑似谣言"
RISK_LEVEL_HIGH = "高风险谣言"

TRUSTED_SCORE_THRESHOLD = 80
SUSPICIOUS_SCORE_THRESHOLD = 60
# score < RUMOR_SCORE_THRESHOLD 时为高风险谣言；score >= RUMOR_SCORE_THRESHOLD 时至少为疑似谣言。
RUMOR_SCORE_THRESHOLD = 40
